@REM
@REM Copyright (c) Microsoft Corporation.  All rights reserved.
@REM
@REM
@REM Use of this source code is subject to the terms of the Microsoft end-user
@REM license agreement (EULA) under which you licensed this SOFTWARE PRODUCT.
@REM If you did not accept the terms of the EULA, you are not authorized to use
@REM this source code. For a copy of the EULA, please see the LICENSE.RTF on your
@REM install media.
@REM
@ECHO OFF

echo Please partition you Hard Disk with fdisk.exe
echo Then format it using format.com
echo then Run:
echo      mkdisk Drive:
echo e.g. mkdisk c:
