#ifndef PLEXON_WRAPPER_DEFS_H_
#define PLEXON_WRAPPER_DEFS_H_

enum PlexonCallType : int
{
	NO_CALL_TYPE = 0,
	CALL,
	RESPONSE,
	PLEXON_CALL_TYPE_MAX
};


enum PlexonFunctionCall : int
{
	NO_CALL = 0,
	CLOSE_CLIENT,
	INIT_CLIENT_EX3,
	IS_SORT_CLIENT_RUNNING,
	GET_TIME_STAMP_TICK,
	GET_SLOW_INFO,
	GET_GAIN,
	GET_LONG_WAVE_FORM_STRUCTURES,
	GET_TIME_STAMP_STRUCTURES,
	QUIT,
	PLEXON_CALL_MAX
};

#endif